name: Accessibility Tools
type: Drupal CMS
description: Adds automated checks to help ensure content conforms to web accessibility guidelines.
recipes:
  - drupal_cms_admin_ui
  - drupal_cms_page
install:
  - editoria11y
config:
  strict: false
  import:
    editoria11y: '*'
  actions:
    editoria11y.settings:
      simpleConfigUpdate:
        # Map tiles contain no alt text.
        # Skipping the map pane to limit reports
        # where the fix is outwith editors control.
        ignore_elements: '.leaflet-map-pane *'
    dashboard.dashboard.welcome:
      addComponentToLayout:
        section: 0
        position: 2
        component:
          region:
            layout_twocol_section: first
          default_region: content
          configuration:
            id: views_block:a11y_tools_editoria11y_results-block_a11y_alerts
            label: ''
            label_display: visible
            provider: views
            context_mapping: { }
            views_label: ''
            items_per_page: null
